/**
 * Copyright 2012 Tejeswar Das
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/**
 * This file was auto-generated by dovemq gentools.
 * Do not modify.
 */
package net.dovemq.transport.protocol.data;

import net.dovemq.transport.protocol.*;

public class CAMQPControlClose
{
    public static final String descriptor = "amqp:close:list";

    private boolean isSetError = false;
    public void setRequiredError(boolean val)
    {
        isSetError = val;
    }
    public boolean isSetError()
    {
        return isSetError;
    }
    private CAMQPDefinitionError error = null;
    public void setError(CAMQPDefinitionError val)
    {
        isSetError = true;
        error = val;
    }

    public CAMQPDefinitionError getError()
    {
        return error;
    }

    public static void encode(CAMQPEncoder encoder, CAMQPControlClose data)
    {
        long listSize = 1;
        encoder.writeListDescriptor(descriptor, listSize);
        if ((data.error != null) && (data.isSetError))
        {
            CAMQPDefinitionError.encode(encoder, data.error);
        }
        else
        {
            encoder.writeNull();
        }
        encoder.fillCompoundSize(listSize);
    }
    public static CAMQPControlClose decode(CAMQPSyncDecoder decoder)
    {
        int formatCode;
        formatCode = decoder.readFormatCode();
        assert((formatCode == CAMQPFormatCodes.LIST8) || (formatCode == CAMQPFormatCodes.LIST32));

        long listSize = decoder.readCompoundSize(formatCode);
        assert(listSize == 1);
        CAMQPControlClose data = new CAMQPControlClose();

        if (decoder.isNextDescribedConstructor())
        {
            String controlName = decoder.readSymbol();
            assert(controlName.equalsIgnoreCase(CAMQPDefinitionError.descriptor));
            data.error = CAMQPDefinitionError.decode(decoder);
            data.isSetError = true;
        }
        else
        {
            formatCode = decoder.readFormatCode();
            assert (formatCode == CAMQPFormatCodes.NULL);
        }
        return data;
    }
}
